M48
; DRILL file {KiCad 6.0.11} date Sun 04 Aug 2024 09:37:50 PM IST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-04T21:37:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X3.0Y-3.0
X3.0Y-33.068
T2
X36.0Y-18.0
T0
M30
